### ISSUE TITLE
Discuss release workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/AdminTasks#46]
### Description

Need to discuss how to deal with release branch names when creating the branches.

Currently, this is not an issue when it is preview. The next version will ALWAYS be only an increase in the preview number.

When creating a new preview branch for the work for the next release, the preview number will always just increment by 1.  This is not the case with non-preview releases.

A preview number in a preview release is the last number at the end of the version string. 
Example: v1.2.3-preview.4 
                                     ☝🏼here is the preview number

When creating release branches for non-preview releases in the future, the individual numbers major, minor, and patch are unknown and will not be known until all the work to be released is complete.  This is because the work being down might require a breaking, minor, or major change to get the work down.  You can't know what the kind of changes will occur until you do the work.  This means that there is no way to know what the version will really be.  So this means we cannot create the branch until the work is complete.

### Acceptance Criteria

- [ ] Discussion is complete and possible issues have been discovered

### ToDo

- [X] I have added the Admin Task to the _**Admin Tasks**_ project.
- [X] I have added the correct labels.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
