### ISSUE TITLE
Checkout FeedHive alternatives

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/AdminTasks#58]
### Description

Hoot suite

### Acceptance Criteria

- [ ] Research is complete

### ToDo

- [X] I have added the Admin Task to the _**Admin Tasks**_ project.
- [X] I have added the correct labels.
