### ISSUE TITLE
Create template repo for apps

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/AdminTasks#9]
- [x] I have updated the title by replacing the '**_<title_**>' section.

### Description
Create a template repo for apps.  They should have default GitHub things setup such as issue and pr template, workflows.
All of the templates and workflows should have various things changed to signify to the user they need to set it up specifically for that project.
No projects should exist in the repo.  Just everything else to make it easier to have things setup once a project is added.

**On Disk Folders:**
![image](https://user-images.githubusercontent.com/85414302/168414726-bfa77c50-e215-4e6f-bea9-49a4e011ec0b.png)

**Solution Virtual Folders:**
![image](https://user-images.githubusercontent.com/85414302/168414499-2adc65fc-f95b-4a4f-868e-437e8b2e687c.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Create on disk folder structure
- [ ] Create solution folder structure

**Pull Request Templates Created:**
- [ ] bug-issue-template.yml
- [ ] config.yml
- [ ] feature-request-issue-template.yml
- [ ] project-item-issue-template.yml 
- [ ] qa-testing-template.yml
- [ ] release-todo-issue-template.yml

**Pull Request Templates Created:**
- [ ] feature-pr.md
- [ ] preview-feature-pr.md
- [ ] preview-release-pr.md
- [ ] production-release-pr.md

**Workflows Created:**
- [ ] build-status-check.yml
- [ ] feature-pr-branches-status-check.yml
- [ ] tag-does-not-exist-status-check.yml
  - [ ] Rename this to `label-exists-status-check.yml`
- [ ] triage-issue.yml
- [ ] unit-testing-status-check.yml
- [ ] validate-feature-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] validate-prev-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] validate-prev-feature-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] validate-release-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] validate-master-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] validate-develop-branch-status-check.yml
  - This will use the new BranchValidator github action
- [ ] version-status-check.yml

**Other:**
- [ ] Go through each file and replace anything that is **Velaptor** or project specific with filler values
- [ ] Setup default DocFX project files and folders
- [ ] Once **EVERYTHING** has been created, create a **develop** branch from master

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [ ] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone

### Issue Dependencies

- KinsonDigital/Velaptor#259
- KinsonDigital/Velaptor#215
- KinsonDigital/Velaptor#219
- KinsonDigital/Velaptor#253
- KinsonDigital/Velaptor#116
- KinsonDigital/Velaptor#147
- KinsonDigital/issues-repo#3
- KinsonDigital/Velaptor#260
- KinsonDigital/Velaptor#261
- KinsonDigital/Velaptor#266
- KinsonDigital/Velaptor#267
- KinsonDigital/Velaptor#282
- KinsonDigital/Velaptor#283
- KinsonDigital/Velaptor#284
- KinsonDigital/Velaptor#286

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
I am not able to remove the "has dependencies" label.
